### ISSUE TITLE
Você usa mais alguns packages?

### ISSUE THREAD

**Issue by luisfmsouza** [lnfnunes/dotfiles#1]
Você não usa Editor Config, Sublime Linter, etc?

**Comment by lnfnunes** [comment]
Uso sim! Estou atualizando aqui aos poucos...
Subi esses pra testar a instalação via _setup-front.sh_
Vou migrar as coisas [desse meu outro repo](https://github.com/lnfnunes/sublime-config) eu acho.

**Comment by luisfmsouza** [comment]
Hum...

Eu usei pra fazer setup do meu note novo :)

On Saturday, 7 November 2015, Leandro Nunes notifications@github.com
wrote:

> Uso sim! Estou atualizando aqui aos poucos...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lnfnunes/dotfiles/issues/1#issuecomment-154709199.

## 

Att,

_Luís Felipe Souza_

**Comment by lnfnunes** [comment]
Esse script? Sério?!!! :D
E rodou tudo balinha? Se tiver alguma sugestão manda aí ;-)

**Comment by luisfmsouza** [comment]
Fiz só um teste pra ver como rodava. A versão que eu executei foi sem instalação do VIM e do SVN, e rodou certinho.

Os packages que eu to usando no momento são:

```
        "Color Highlighter",
        "CursorRuler",
        "EditorConfig",
        "Emmet",
        "Git",
        "GitGutter",
        "Package Control",
        "Sass",
        "SublimeLinter",
        "WakaTime"
```

**Comment by lnfnunes** [comment]
Done, tks!
